# Generated by Django 4.0.5 on 2024-05-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patitasLove', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='producto'),
        ),
    ]
